Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\Users\asus\Desktop\Work\SaleOfBooks\src\WebApp
[1/10/2021 8:30:10 AM]:[book/listfavoritebook]:[type:get]:[info:list favorite book]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
[1/10/2021 8:30:12 AM]:[book/index]:[type:get]:[info:index]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
1/10/2021 8:30:13 AM: Something went wrong: Core.Exceptions.ValidationException: Book with id 34334 not found
   at Core.Services.BookService.GetBook(Nullable`1 id) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\Core\Services\BookService.cs:line 34
   at WebApp.Controllers.BookController.GetBookInfo(Int32 id, String sortString, String stringGenre, String searchFor, String nameSearch, Boolean isDisplay) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\WebApp\Controllers\BookController.cs:line 254
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at WebApp.Exceptions.ExceptionInterceptor.InvokeAsync(HttpContext context) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\WebApp\Exceptions\ExceptionInterceptor.cs:line 24
An unhandled exception has occurred while executing the request.
[1/10/2021 8:30:14 AM]:[home/error/&]:[type:get]:[info:error code:  info: ]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
[1/10/2021 8:30:16 AM]:[book/index]:[type:get]:[info:index]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
1/10/2021 8:30:17 AM: Something went wrong: Core.Exceptions.ValidationException: Book with id 34334 not found
   at Core.Services.BookService.GetBook(Nullable`1 id) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\Core\Services\BookService.cs:line 34
   at WebApp.Controllers.BookController.GetBookInfo(Int32 id, String sortString, String stringGenre, String searchFor, String nameSearch, Boolean isDisplay) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\WebApp\Controllers\BookController.cs:line 254
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at WebApp.Exceptions.ExceptionInterceptor.InvokeAsync(HttpContext context) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\WebApp\Exceptions\ExceptionInterceptor.cs:line 24
An unhandled exception has occurred while executing the request.
[1/10/2021 8:30:17 AM]:[home/error/&]:[type:get]:[info:error code:  info: ]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
[1/10/2021 8:30:19 AM]:[book/index]:[type:get]:[info:index]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
1/10/2021 8:30:20 AM: Something went wrong: Core.Exceptions.ValidationException: Book with id 34334 not found
   at Core.Services.BookService.GetBook(Nullable`1 id) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\Core\Services\BookService.cs:line 34
   at WebApp.Controllers.BookController.GetBookInfo(Int32 id, String sortString, String stringGenre, String searchFor, String nameSearch, Boolean isDisplay) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\WebApp\Controllers\BookController.cs:line 254
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at WebApp.Exceptions.ExceptionInterceptor.InvokeAsync(HttpContext context) in C:\Users\asus\Desktop\Work\SaleOfBooks\src\WebApp\Exceptions\ExceptionInterceptor.cs:line 24
An unhandled exception has occurred while executing the request.
[1/10/2021 8:30:20 AM]:[home/error/&]:[type:get]:[info:error code:  info: ]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
[1/10/2021 8:30:22 AM]:[book/index]:[type:get]:[info:index]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
Hosting environment: Development
Content root path: C:\Users\asus\Desktop\Work\SaleOfBooks\src\WebApp
[1/10/2021 8:32:06 AM]:[book/listfavoritebook]:[type:get]:[info:list favorite book]:[user:3c626483-1539-4dca-ac18-8f7a68aae25e]
